apiVersion: v1
kind: Service
metadata:
  name: minio-proj
  namespace: minio-ns
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: http  # Name for the first port (port 9000)
      port: 9000
      targetPort: 9000
    - name: console  # Name for the second port (port 9001)
      port: 9001
      targetPort: 9001
